
service: fargatePython
frameworkVersion: "2"
configValidationMode: error
provider:
  name: aws
  lambdaHashingVersion: 20201221
  stage: dev
  ecr:
    images:
      fargate-python-image:
        path: "./"

functions:
  fargatePython:
    image: fargate-python-image
    events:
      - schedule: cron(0 09 * * ? *)
